baseurl = "https://rudradevsengupta.netlify.com/"
title = "Rudradev Sengupta"
canonifyurls = true
relativeurls = false
paginate = 10
theme = "robjhyndman"
DisqusShortname = "researchtips"
googleAnalytics = "UA-5004894-1"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
pluralizeListTitles = false
buildFuture = true

[params]

# Date format (refer to Go's date format: http://flippinggodateformat.com)
date_format = "2 January 2006"

# Number of posts to show on main page.
posts_count = 2

# Number of publications to show on main page.
pubs_count = 2

# Number of posts to show on main page.
seminars_count = 2

# options for highlight.js (version, additional languages, and theme)
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"

[[params.social]]
  icon = "university"
  icon_pack = "fa"
 # link = "https://www.monash.edu/business/ebs"
  text = "Scientific Computing Group - Janssen: Pharmaceutical Companies of Johnson & Johnson, Turnhoutseweg 30, Beerse, 2340 Belgium."

[[params.social]]
  icon = "envelope"
  icon_pack = "fa"
  link = "mailto:rsengup4@its.jnj.com"
  text = "rsengup4@its.jnj.com"


# Navigation Links
# The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "/publications/"
  weight = 2

[[menu.main]]
  name = "Software"
  url = "/software/"
  weight = 3

[[menu.main]]
  name = "Seminars"
  url = "/seminars/"
  weight = 4

[[menu.main]]
  name = "Teaching"
  url = "/teaching/"
  weight = 5


