baseurl = "https://robjhyndman.com/"
title = "Rob J Hyndman"
canonifyurls = true
relativeurls = false
paginate = 10
theme = "robjhyndman"
DisqusShortname = "researchtips"
googleAnalytics = "UA-5004894-1"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
pluralizeListTitles = false
buildFuture = true

[params]

# Date format (refer to Go's date format: http://flippinggodateformat.com)
date_format = "2 January 2006"

# Number of posts to show on main page.
posts_count = 2

# Number of publications to show on main page.
pubs_count = 4

# Number of posts to show on main page.
seminars_count = 4

# options for highlight.js (version, additional languages, and theme)
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"

[[params.social]]
  icon = "university"
  icon_pack = "fa"
  link = "https://www.monash.edu/business/ebs"
  text = "Department of Econometrics & Business Statistics, Monash University, Clayton VIC 3800, Australia."

[[params.social]]
  icon = "envelope"
  icon_pack = "fa"
  link = "mailto:Rob.Hyndman@monash.edu"
  text = "Rob.Hyndman@monash.edu"

[[params.social]]
  icon = "twitter"
  icon_pack = "fa"
  link = "https://twitter.com/robjhyndman"
  text = "@robjhyndman"
  site = "Twitter"

[[params.social]]
  icon = "github-alt"
  icon_pack = "fa"
  link = "https://github.com/robjhyndman/"
  text = "robjhyndman"
  site = "GitHub"

[[params.social]]
  icon = "google-scholar"
  icon_pack = "ai"
  link = "https://scholar.google.com/citations?user=vamErfkAAAAJ"
  text = "Google Scholar"



# Navigation Links
# The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Hyndsight blog"
  url = "/hyndsight/"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "/publications/"
  weight = 2

[[menu.main]]
  name = "Software"
  url = "/software/"
  weight = 3

[[menu.main]]
  name = "Seminars"
  url = "/seminars/"
  weight = 4

[[menu.main]]
  name = "Teaching"
  url = "/teaching/"
  weight = 4

[[menu.main]]
  name = "Research team"
  url = "/research-team/"
  weight = 5

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 6

